/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agenda.view;

import br.com.agenda.bens.Contato;
import br.com.agenda.bens.Telefone;
import br.com.agenda.bens.TipoContato;
import br.com.agenda.dao.ContatoDao;
import br.com.agenda.dao.TelefoneDao;
import br.com.agenda.dao.TipoContatoDao;
import br.com.agenda.daoimpl.ContatoDaoImpl;
import br.com.agenda.daoimpl.TelefoneDaoImpl;
import br.com.agenda.daoimpl.Principal;
import br.com.agenda.daoimpl.TipoContatoDaoImpl;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xAcer
 */
public class FormularioContato extends javax.swing.JPanel {

    /**
     * Creates new form FormularioContato
     */
    private static Contato contato;
    private static Telefone telefone;
    private static TipoContato tipoContato;
    private static ContatoDao contatoDao;
    private static TelefoneDao telefoneDao;
    private static TipoContatoDao tipoContatoDao;
    private static SimpleDateFormat df;
    private static List<Telefone> telefones;
    private static Integer contatoAlterar;

    public FormularioContato(Contato c) {

        tipoContatoDao = new TipoContatoDaoImpl();
        telefoneDao = new TelefoneDaoImpl();
        df = new SimpleDateFormat("dd/MM/yyyy");
        telefones = new ArrayList();
        initComponents();
        telefones = new ArrayList();
        adicionarNumeroTelefonesTabela(telefones);
        if (c != null) {
            tfNome.setText(c.getNome() == null ? "" : c.getNome());
            tfEmail.setText(c.getEmail() == null ? "" : c.getEmail());
            formatNascimento.setText(c.getDataNascimento() == null ? "" : df.format(c.getDataNascimento()));
            tfDdd.setText(null);
            tfNumeroTelefone.setText(null);
            adicionarNumeroTelefonesTabela(c.getTelefones() == null ? telefones : c.getTelefones());
            telefones = c.getTelefones();
            contatoAlterar = c.getId();
        }
        try {
            List<Object> pesquisarTodos = tipoContatoDao.pesquisarTodos();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel(pesquisarTodos.toArray());
            cbTipo.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        formatNascimento = new javax.swing.JFormattedTextField();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfDdd = new javax.swing.JTextField();
        tfNumeroTelefone = new javax.swing.JTextField();
        bMais = new javax.swing.JButton();
        bMenos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTelefones = new javax.swing.JTable();
        bGravar = new javax.swing.JButton();
        comboBoxTipoCelular = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(444, 300));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Contato");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel3.setText("Nascimento");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel4.setText("E-mail");

        tfNome.setColumns(15);
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfEmail.setColumns(15);

        try {
            formatNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatNascimento.setPreferredSize(new java.awt.Dimension(126, 20));
        formatNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatNascimentoActionPerformed(evt);
            }
        });

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipo.setMinimumSize(new java.awt.Dimension(126, 20));
        cbTipo.setPreferredSize(new java.awt.Dimension(126, 20));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel5.setText("Tipo");

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 200));

        tfDdd.setPreferredSize(new java.awt.Dimension(20, 20));
        tfDdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDddActionPerformed(evt);
            }
        });
        tfDdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDddKeyPressed(evt);
            }
        });

        tfNumeroTelefone.setPreferredSize(new java.awt.Dimension(60, 20));

        bMais.setText("+");
        bMais.setPreferredSize(new java.awt.Dimension(20, 20));
        bMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMaisActionPerformed(evt);
            }
        });

        bMenos.setText("-");
        bMenos.setMaximumSize(new java.awt.Dimension(40, 23));
        bMenos.setPreferredSize(new java.awt.Dimension(40, 20));
        bMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenosActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefones Adicionados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(250, 125));

        tableTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DDD", "Numero", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTelefones);
        if (tableTelefones.getColumnModel().getColumnCount() > 0) {
            tableTelefones.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        bGravar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bGravar.setText("Gravar");
        bGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGravarActionPerformed(evt);
            }
        });

        comboBoxTipoCelular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celular", "Residencial", "Trabalho" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxTipoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(tfDdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bMais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addComponent(bGravar)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(comboBoxTipoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bGravar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))))
        );

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel6.setText("Telefones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formatNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1)))
                .addGap(0, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(formatNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGravarActionPerformed
        if (tfNome.getText().isEmpty() || formatNascimento.getText().isEmpty()
                || tfEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatorios!");

        } else {
            contato = new Contato();
            try {
                contato.setId(WIDTH);
                contato.setNome(tfNome.getText());
                contato.setEmail(tfEmail.getText());
                contato.setDataNascimento(df.parse(formatNascimento.getText()));
                tipoContato = (TipoContato) cbTipo.getSelectedItem();
                contato.setTipoContato(tipoContato);
                if (telefones != null) {
                    contato.setTelefones(telefones);
                }
                contatoDao = new ContatoDaoImpl();
                if (contatoAlterar == null) {
                    if (contatoDao.inserir(contato)) {
                        Integer escolha = JOptionPane.showConfirmDialog(null, "Contato Adicionado com Sucesso\n"
                                + "Deseja Adicionar outro Contato?", " ", JOptionPane.YES_NO_OPTION);
                        contato = null;
                        if (escolha.equals(0)) {
                            limparCampos();
                        } else {
                            Principal.listarContatos();
                        }
                    }
                } else {
                    contato.setId(contatoAlterar);
                    if (contatoDao.update(contato)) {
                        JOptionPane.showMessageDialog(null, "Contato Alterado com Sucesso");
                        Principal.listarContatos();
                        contato = null;
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bGravarActionPerformed

    private void formatNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatNascimentoActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfDddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDddActionPerformed

    private void bMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMaisActionPerformed
        if (telefones == null) {
            telefones = new ArrayList<>();
        }
        if (tfDdd.getText().length() > 2 || tfDdd.getText().isEmpty()
                || tfNumeroTelefone.getText().length() > 10 || tfNumeroTelefone.getText().isEmpty()
                || !isNumber(tfNumeroTelefone.getText().toString())) {
            JOptionPane.showMessageDialog(null, "Campos Vazios não Sao aceitos\nDDD Com 2 Numeros\nTelefone com até 10 numeros");
        } else {
            for (Telefone telefone1 : telefones) {
                if (telefone1.getNumero().equalsIgnoreCase(tfNumeroTelefone.getText())) {
                    JOptionPane.showMessageDialog(null, "Esse Numero ja existe");
                    return;
                }
            }
            telefone = new Telefone();
            telefone.setDDD(tfDdd.getText());
            telefone.setNumero(tfNumeroTelefone.getText());
            telefone.setTipo(comboBoxTipoCelular.getItemAt(comboBoxTipoCelular.getSelectedIndex()));
            telefones.add(telefone);
            adicionarNumeroTelefonesTabela(telefones);

        }
    }//GEN-LAST:event_bMaisActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed

    }//GEN-LAST:event_cbTipoActionPerformed

    private void bMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenosActionPerformed
        int linha = tableTelefones.getSelectedRow();
        if (linha >= 0) {
            try {
                String stringNumero = (String) tableTelefones.getValueAt(linha, 1);
                telefoneDao.excluir(stringNumero);
            } catch (Exception e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
            telefones.remove(linha);
            adicionarNumeroTelefonesTabela(telefones);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bMenosActionPerformed

    private void tfDddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDddKeyPressed
    }//GEN-LAST:event_tfDddKeyPressed
    public void adicionarNumeroTelefonesTabela(List<Telefone> telefones) {
        String[] colunas = {"DDD", "Numero", "Tipo"};
        String[][] dados = new String[telefones.size()][colunas.length];
        for (int i = 0; i < telefones.size(); i++) {
            Telefone t = telefones.get(i);
            dados[i][0] = t.getDDD();
            dados[i][1] = t.getNumero();
            dados[i][2] = t.getTipo();
        }
        DefaultTableModel modelo = new DefaultTableModel(dados, colunas);
        tableTelefones.setModel(modelo);
    }

    public void limparCampos() {
        tfNome.setText(null);
        tfEmail.setText(null);
        formatNascimento.setText(null);
        tfDdd.setText(null);
        tfNumeroTelefone.setText(null);
        telefones = new ArrayList<>();
        adicionarNumeroTelefonesTabela(telefones);
    }

    private boolean isNumber(String str) {
        Pattern p = Pattern.compile("[0-9]+");
        Matcher m = p.matcher(str);
        return m.find();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGravar;
    private javax.swing.JButton bMais;
    private javax.swing.JButton bMenos;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> comboBoxTipoCelular;
    private javax.swing.JFormattedTextField formatNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTelefones;
    private javax.swing.JTextField tfDdd;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumeroTelefone;
    // End of variables declaration//GEN-END:variables
}
