/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agenda.view;

import br.com.agenda.bens.Telefone;
import br.com.agenda.bens.TipoContato;
import br.com.agenda.dao.TipoContatoDao;
import br.com.agenda.daoimpl.TipoContatoDaoImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class FormularioTipoContato extends javax.swing.JPanel {

    /**
     * Creates new form FormularioTipoContato
     */
    public static TipoContatoDao tipoContatoDao;
    public static List<TipoContato> tipoContatos;
    public static TipoContato tipoContato;

    public FormularioTipoContato() {
        initComponents();
        tipoContatos = new ArrayList<>();
        tipoContatoDao = new TipoContatoDaoImpl();
        try {
            List lista = tipoContatoDao.pesquisarTodos();
            for (Object object : lista) {
                tipoContato = (TipoContato) object;
                tipoContatos.add(tipoContato);
            }
            adicionarTiposNaTabela(tipoContatoDao.pesquisarTodos());
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTipos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTipo = new javax.swing.JTextField();
        bAdd = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();

        tableTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Tipos"
            }
        ));
        jScrollPane1.setViewportView(tableTipos);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Tipo de Contatos");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Nome");

        tfTipo.setPreferredSize(new java.awt.Dimension(100, 20));
        tfTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipoActionPerformed(evt);
            }
        });

        bAdd.setText("Adicionar");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bRemover.setText("Remover");
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bRemover)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bAdd))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAdd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void tfTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipoActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        tipoContato = new TipoContato();
        tipoContato.setTipo(tfTipo.getText());
        tipoContatos.add(tipoContato);
        try {
            if (tipoContatoDao.inserir(tipoContato)) {
                JOptionPane.showMessageDialog(null, "Salvo com Sucesso");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar" + e.getMessage());
            e.printStackTrace();
        }
        adicionarTiposNaTabela(tipoContatos);
        tfTipo.setText("");
    }//GEN-LAST:event_bAddActionPerformed

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        int linha = tableTipos.getSelectedRow();
        if (linha >= 0) {
            try {
                String idString = (String) tableTipos.getValueAt(linha, 0);
                Integer id = Integer.valueOf(idString);
                if (tipoContatoDao.excluir(id)) {
                    JOptionPane.showMessageDialog(null, "Excluido com Sucesso");
                    tipoContatos.remove(linha);
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao excluir!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                e.getMessage();
            }
            adicionarTiposNaTabela(tipoContatos);
        }else{
            JOptionPane.showMessageDialog(null, "Seleciona na Tabela o Tipo a ser removido");
        }
    }//GEN-LAST:event_bRemoverActionPerformed

    public void adicionarTiposNaTabela(List list) {

        String[] colunas = {"ID", "Tipo"};
        String[][] dados = new String[list.size()][colunas.length];
        for (int i = 0; i < list.size(); i++) {
            TipoContato t = (TipoContato) list.get(i);
            dados[i][0] = t.getId().toString();
            dados[i][1] = t.getTipo();
        }
        DefaultTableModel modelo = new DefaultTableModel(dados, colunas);
        tableTipos.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTipos;
    private javax.swing.JTextField tfTipo;
    // End of variables declaration//GEN-END:variables
}
